[package]
name = "rectangle_area"
version = "0.1.0"
authors = ["remde <ffremde@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
